paths:
  "/wellness/myprofile":
    get:
      tags:
        - wellness.Profile
      summary: Get user's profile
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success
