paths:
  "/mentalHealth/quizzes/wheeloflife":
    get:
      tags:
        - mentalHealth-Quiz
      summary: Get wheel of life quiz
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful Login
        400:
          description: Authentication failed
