paths:
  "/mentalHealth/quizanswers/wheeloflife":
    post:
      tags:
        - mentalHealth-QuizAnswer
      summary: Create new quiz of wheel of life answer
      description: |
        La idea es usar como body el objeto categories que se obtiene del endpoint /quiz/wheeloflife
        y reemplazar el campo answerFormat por la respuesta a la respectiva pregunta.

        Revisar ejemplo de body en [ejemplo](https://jsoneditoronline.org/#left=cloud.83d246d1095847f68b4dbed87cea6d4d)
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                categories:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      questions:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            description:
                              type: string
                            answer:
                              type: integer
      responses:
        200:
          description: Successful Login
        400:
          description: Authentication failed
