paths:
  "/mentalHealth/modules":
    get:
      tags:
        - mentalHealth-Module
      summary: Get modules for mental health section
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful Login
        400:
          description: Authentication failed
  "/mentalHealth/modules/{id}":
    get:
      tags:
        - mentalHealth-Module
      summary: Get one module by Id
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/paramId"
      responses:
        200:
          description: Successful Login
        400:
          description: Authentication failed
